/* Downloads the latin subsets of the UI typefaces into static/fonts/ and writes
   the matching @font-face rules to src/fonts.css.
   Run: npm run fonts
   Result is committed to the repo so the Flask app never talks to a CDN. */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = new URL('../static/fonts/', import.meta.url).pathname;
const CSS_OUT = new URL('../src/fonts.css', import.meta.url).pathname;

/* Only Latin is vendored: the UI ships English copy and the fallback stack
   handles anything else. Drop a subset from this list to stop shipping it. */
const KEEP = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  { name: 'IBM Plex Sans', query: 'IBM+Plex+Sans:wght@400;500' },
  { name: 'IBM Plex Mono', query: 'IBM+Plex+Mono:wght@400;500' },
  { name: 'Archivo', query: 'Archivo:wdth,wght@62..125,400..700' },
];

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const blocks = [];

  for (const family of FAMILIES) {
    const url =
      'https://fonts.googleapis.com/css2?family=' +
      family.query +
      '&display=swap';
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${family.name}: HTTP ${res.status}`);
    const css = await res.text();

    /* Google returns `/* subset *\/` immediately before each @font-face. */
    const parts = css.split('/*').slice(1);
    let index = 0;

    for (const part of parts) {
      const subset = part.slice(0, part.indexOf('*/')).trim();
      if (!KEEP.has(subset)) continue;

      const face = part.slice(part.indexOf('*/') + 2).trim();
      const href = face.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!href) continue;

      const weight = face.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? '400';
      const stretch = face.match(/font-stretch:\s*([^;]+);/)?.[1]?.trim();
      const file = `${slug(family.name)}-${slug(weight)}${
        stretch ? '-' + slug(stretch) : ''
      }-${slug(subset)}.woff2`;

      const bin = await fetch(href[1], { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`${file}: HTTP ${bin.status}`);
      const bytes = Buffer.from(await bin.arrayBuffer());
      await writeFile(join(OUT_DIR, file), bytes);

      blocks.push(
        face
          .replace(/url\(https:\/\/[^)]+\)/, `url("fonts/${file}")`)
          .replace(/^\s*\n/gm, '\n')
          .replace(/;\s+/g, ';\n  ')
      );
      console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} KB  (${subset})`);
      index++;
    }
    if (!index) throw new Error(`${family.name}: no latin faces found`);
  }

  await writeFile(
    CSS_OUT,
    '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n' +
      blocks.join('\n\n') +
      '\n'
  );
  console.log(`\n${blocks.length} faces -> static/fonts/ + src/fonts.css`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
